// source: plugins/service/service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var google_protobuf_descriptor_pb = require('google-protobuf/google/protobuf/descriptor_pb.js');
goog.object.extend(proto, google_protobuf_descriptor_pb);
goog.exportSymbol('proto.service.Boolean', null, global);
goog.exportSymbol('proto.service.Field', null, global);
goog.exportSymbol('proto.service.crud', null, global);
goog.exportSymbol('proto.service.field', null, global);
goog.exportSymbol('proto.service.tablename', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.service.Field = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.service.Field, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.service.Field.displayName = 'proto.service.Field';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.service.Field.prototype.toObject = function(opt_includeInstance) {
  return proto.service.Field.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.service.Field} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.service.Field.toObject = function(includeInstance, msg) {
  var f, obj = {
    uppernospacenoaccent: jspb.Message.getFieldWithDefault(msg, 1, 0),
    uppercase: jspb.Message.getFieldWithDefault(msg, 2, 0),
    trimspace: jspb.Message.getFieldWithDefault(msg, 3, 0),
    removeaccent: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.service.Field}
 */
proto.service.Field.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.service.Field;
  return proto.service.Field.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.service.Field} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.service.Field}
 */
proto.service.Field.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.service.Boolean} */ (reader.readEnum());
      msg.setUppernospacenoaccent(value);
      break;
    case 2:
      var value = /** @type {!proto.service.Boolean} */ (reader.readEnum());
      msg.setUppercase(value);
      break;
    case 3:
      var value = /** @type {!proto.service.Boolean} */ (reader.readEnum());
      msg.setTrimspace(value);
      break;
    case 4:
      var value = /** @type {!proto.service.Boolean} */ (reader.readEnum());
      msg.setRemoveaccent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.service.Field.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.service.Field.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.service.Field} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.service.Field.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUppernospacenoaccent();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getUppercase();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getTrimspace();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getRemoveaccent();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
};


/**
 * optional Boolean upperNoSpaceNoAccent = 1;
 * @return {!proto.service.Boolean}
 */
proto.service.Field.prototype.getUppernospacenoaccent = function() {
  return /** @type {!proto.service.Boolean} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.service.Boolean} value
 * @return {!proto.service.Field} returns this
 */
proto.service.Field.prototype.setUppernospacenoaccent = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional Boolean upperCase = 2;
 * @return {!proto.service.Boolean}
 */
proto.service.Field.prototype.getUppercase = function() {
  return /** @type {!proto.service.Boolean} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.service.Boolean} value
 * @return {!proto.service.Field} returns this
 */
proto.service.Field.prototype.setUppercase = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional Boolean trimSpace = 3;
 * @return {!proto.service.Boolean}
 */
proto.service.Field.prototype.getTrimspace = function() {
  return /** @type {!proto.service.Boolean} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.service.Boolean} value
 * @return {!proto.service.Field} returns this
 */
proto.service.Field.prototype.setTrimspace = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional Boolean removeAccent = 4;
 * @return {!proto.service.Boolean}
 */
proto.service.Field.prototype.getRemoveaccent = function() {
  return /** @type {!proto.service.Boolean} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.service.Boolean} value
 * @return {!proto.service.Field} returns this
 */
proto.service.Field.prototype.setRemoveaccent = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * @enum {number}
 */
proto.service.Boolean = {
  UNSPECIFIED: 0,
  YES: 1,
  NO: 2
};


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `crud`.
 * @type {!jspb.ExtensionFieldInfo<boolean>}
 */
proto.service.crud = new jspb.ExtensionFieldInfo(
    1000,
    {crud: 0},
    null,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         null),
    0);

google_protobuf_descriptor_pb.MessageOptions.extensionsBinary[1000] = new jspb.ExtensionFieldBinaryInfo(
    proto.service.crud,
    jspb.BinaryReader.prototype.readBool,
    jspb.BinaryWriter.prototype.writeBool,
    undefined,
    undefined,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.MessageOptions.extensions[1000] = proto.service.crud;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `tablename`.
 * @type {!jspb.ExtensionFieldInfo<string>}
 */
proto.service.tablename = new jspb.ExtensionFieldInfo(
    1001,
    {tablename: 0},
    null,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         null),
    0);

google_protobuf_descriptor_pb.MessageOptions.extensionsBinary[1001] = new jspb.ExtensionFieldBinaryInfo(
    proto.service.tablename,
    jspb.BinaryReader.prototype.readString,
    jspb.BinaryWriter.prototype.writeString,
    undefined,
    undefined,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.MessageOptions.extensions[1001] = proto.service.tablename;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `field`.
 * @type {!jspb.ExtensionFieldInfo<!proto.service.Field>}
 */
proto.service.field = new jspb.ExtensionFieldInfo(
    1001,
    {field: 0},
    proto.service.Field,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.service.Field.toObject),
    0);

google_protobuf_descriptor_pb.FieldOptions.extensionsBinary[1001] = new jspb.ExtensionFieldBinaryInfo(
    proto.service.field,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.service.Field.serializeBinaryToWriter,
    proto.service.Field.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.FieldOptions.extensions[1001] = proto.service.field;

goog.object.extend(exports, proto.service);
