isRequired = "{{ .Name }} é obrigatório"
isByteLength = "{{ .Name }} ({{ .CurrentValue }}) precisa ter entre {{ .Value1 }} caracteres e {{ .Value2 }}, ele possui {{ .Count }}"
inRangeFloat = "{{ .Name }} precisa ser entre entre {{ .Value1 }} e {{ .Value2 }}, valor atual {{ .CurrentValue }}"
inRangeInt = "{{ .Name }}  precisa ser entre entre {{ .Value1 }} e {{ .Value2 }}, valor atual {{ .CurrentValue }}"
equalsFloat = "{{ .Name }} precisa ser igual a {{ .Value }}, valor atual é {{ .CurrentValue }}"
isObjectId = "{{ .Name }} nao é um ObjectID válido"
isEmailValid = "Campo {{ .Name }} \"{{ .Value }}\" nao é um email válido"
isGreaterThan = "Campo {{ .Name }} precisa ser maior que \"{{ .Value }}\""
isOnlyNumber = "Campo {{ .Name }} só pode conter números "
isNotValid = "Campo {{ .Name }} nao é válido com o valor \"{{ .Value }}\" "
isNotUrlValid = "Campo {{ .Name }} nao é uma URL válida com o valor \"{{ .CurrentValue }}\" "
isIn = "Campo {{ .Name }} precisa ser um desses valores \"{{ .Value }}\" "
isByteMinLength = "Campo {{ .Name }} nao é uma URL válida com o valor \"{{ .CurrentValue }}\" "
isByteMaxLength = "Campo {{ .Name }} precisa ter no máximo \"{{ .Value }}\", ele possui   \"{{ .CurrentValue }}\""