isRequired = "%s is required"
isByteLength = "%s (%s) needs to be between %d and %d, it currently has %d"
inRangeFloat = "%s needs to be between %f and %f, current value is %f"
inRangeInt = "%s needs to be between %d and %d, current value is %d"
equalsFloat = "%s needs to be equal to %f, current value is %f"
isObjectId = "%s is not a valid ObjectID"
isEmailValid = "Field %s \"%s\" is not a valid email"
isGreaterThan = "Field %s needs to be greater than \"%s\""
isOnlyNumber = "Field %s can only contain numbers"
isNotValid = "Field %s is not valid with value \"%s\""
isNotUrlValid = "Field %s is not a valid URL with value \"%s\""
