// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protos/report.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace FastReportApp {

  /// <summary>Holder for reflection information generated from protos/report.proto</summary>
  public static partial class ReportReflection {

    #region Descriptor
    /// <summary>File descriptor for protos/report.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ReportReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNwcm90b3MvcmVwb3J0LnByb3RvEgVncmVldCJSChBHZXRSZXBvcnRSZXF1",
            "ZXN0EhMKC2ZyeF9jb250ZW50GAEgASgJEhAKCGZyeF9kYXRhGAIgASgJEhcK",
            "D291dHB1dF9maWxlbmFtZRgDIAEoCSIhChFHZXRSZXBvcnRSZXNwb25zZRIM",
            "CgRkYXRhGAEgASgMMkgKBnJlcG9ydBI+CglHZXRSZXBvcnQSFy5ncmVldC5H",
            "ZXRSZXBvcnRSZXF1ZXN0GhguZ3JlZXQuR2V0UmVwb3J0UmVzcG9uc2VCEKoC",
            "DUZhc3RSZXBvcnRBcHBiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::FastReportApp.GetReportRequest), global::FastReportApp.GetReportRequest.Parser, new[]{ "FrxContent", "FrxData", "OutputFilename" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FastReportApp.GetReportResponse), global::FastReportApp.GetReportResponse.Parser, new[]{ "Data" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GetReportRequest : pb::IMessage<GetReportRequest> {
    private static readonly pb::MessageParser<GetReportRequest> _parser = new pb::MessageParser<GetReportRequest>(() => new GetReportRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetReportRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FastReportApp.ReportReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetReportRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetReportRequest(GetReportRequest other) : this() {
      frxContent_ = other.frxContent_;
      frxData_ = other.frxData_;
      outputFilename_ = other.outputFilename_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetReportRequest Clone() {
      return new GetReportRequest(this);
    }

    /// <summary>Field number for the "frx_content" field.</summary>
    public const int FrxContentFieldNumber = 1;
    private string frxContent_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FrxContent {
      get { return frxContent_; }
      set {
        frxContent_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "frx_data" field.</summary>
    public const int FrxDataFieldNumber = 2;
    private string frxData_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FrxData {
      get { return frxData_; }
      set {
        frxData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "output_filename" field.</summary>
    public const int OutputFilenameFieldNumber = 3;
    private string outputFilename_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OutputFilename {
      get { return outputFilename_; }
      set {
        outputFilename_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetReportRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetReportRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FrxContent != other.FrxContent) return false;
      if (FrxData != other.FrxData) return false;
      if (OutputFilename != other.OutputFilename) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (FrxContent.Length != 0) hash ^= FrxContent.GetHashCode();
      if (FrxData.Length != 0) hash ^= FrxData.GetHashCode();
      if (OutputFilename.Length != 0) hash ^= OutputFilename.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (FrxContent.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FrxContent);
      }
      if (FrxData.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FrxData);
      }
      if (OutputFilename.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(OutputFilename);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (FrxContent.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FrxContent);
      }
      if (FrxData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FrxData);
      }
      if (OutputFilename.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OutputFilename);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetReportRequest other) {
      if (other == null) {
        return;
      }
      if (other.FrxContent.Length != 0) {
        FrxContent = other.FrxContent;
      }
      if (other.FrxData.Length != 0) {
        FrxData = other.FrxData;
      }
      if (other.OutputFilename.Length != 0) {
        OutputFilename = other.OutputFilename;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            FrxContent = input.ReadString();
            break;
          }
          case 18: {
            FrxData = input.ReadString();
            break;
          }
          case 26: {
            OutputFilename = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetReportResponse : pb::IMessage<GetReportResponse> {
    private static readonly pb::MessageParser<GetReportResponse> _parser = new pb::MessageParser<GetReportResponse>(() => new GetReportResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetReportResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FastReportApp.ReportReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetReportResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetReportResponse(GetReportResponse other) : this() {
      data_ = other.data_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetReportResponse Clone() {
      return new GetReportResponse(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private pb::ByteString data_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetReportResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetReportResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Data != other.Data) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Data.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetReportResponse other) {
      if (other == null) {
        return;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Data = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
