name: SonarCloud - Code quality check

on:
  push:
    paths:
      - 'comps/**'
      - '.github/workflows/sonarcloud.yaml'
jobs:
  SonarCloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=linksoft-dev
          -Dsonar.projectKey=linksoft-dev_single
          -Dsonar.exclusions=**/*.py,**/*.xsd,**/*.xml,**/*.mod;**/*.sum,**/*.bat,**/*.sh,**/*.json
          -Dsonar.test.inclusions=**/*_test.go
          -Dsonar.cpd.exclusions=
          -Dsonar.c.file.suffixes=-
          -Dsonar.cpp.file.suffixes=-
          -Dsonar.objc.file.suffixes=-

